### ISSUE TITLE
Unable to score the speech: key

### ISSUE THREAD

**Issue by owldrak** [speechace/speechace-api-samples#1]
Hey,

So I am trying to figure out how it works, I added the correct key, but still getting the error:

Unable to score the speech: key

Any insights on that?

**Comment by aelshimi** [comment]
Which region is your key in? The sample defaults to us-west. If you're key is in Singapore then in django_sample/score_speech/views.py

api_root_url = 'https://api2.speechace.com'

The api root for your region is specified in the email where you get your API key. You can also test this with curl first to be sure and then update the sample. Hope this helps. Let us know otherwise.

**Comment by owldrak** [comment]
Solved, thanks.
